image: colthreepv/node-chrome:13

cache:
  paths:
    - node_modules/

stages:
  - setup
  - test
  - build

setup:
  stage: setup
  script:
    - rm ./package-lock.json
    - npm install

test:
  stage: test
  script:
    - ./node_modules/@angular/cli/bin/ng test --progress false --watch=false
    - ./node_modules/@angular/cli/bin/ng e2e

build:
  stage: build
  script: ./node_modules/@angular/cli/bin/ng build --progress false --prod

